# Please note not all available settings / options are set here.
# For a full list, see the wiki

$mainMod = ALT

bind = $mainMod, R, exec, hyprctl reload

exec = setxkbmap -layout de -variant nodeadkeys

source =  ~/.config/hypr/hyprland/binds.conf
source =  ~/.config/hypr/hyprland/execs.conf
source =  ~/.config/hypr/hyprland/visual.conf
source =  ~/.config/hypr/hyprland/displays.conf
source =  ~/.config/hypr/hyprland/input.conf
source =  ~/.config/hypr/hyprland/dynamic-cursors.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = HYPRCURSOR_THEME, Future-Cyan-Hyprcursor_Theme
env = HYPRCURSOR_SIZE, 24
env = GDK_SCALE, 0.8
env = XCURSOR_SIZE, 18
env = GDK_DPI_SCALE, 0.85
env = QT_SCALE_FACTOR, 0.85
env = QT_AUTO_SCREEN_SCALE_FACTOR, 0
env = QT_ENABLE_HIGHDPI_SCALING, 1
