# Shell variables
# Generated by 'wal'
wallpaper='/home/tom/.config/i3/assets/gradient.jpg'

# Special
background='#1c2049'
foreground='#c8e2de'
cursor='#c8e2de'

# Colors
color0='#1c2049'
color1='#5AB0C4'
color2='#65CBC9'
color3='#A495B3'
color4='#D99BB2'
color5='#A7B7C3'
color6='#D2AEC6'
color7='#c8e2de'
color8='#8c9e9b'
color9='#5AB0C4'
color10='#65CBC9'
color11='#A495B3'
color12='#D99BB2'
color13='#A7B7C3'
color14='#D2AEC6'
color15='#c8e2de'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
