--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/tom/.config/i3/assets/gradient.jpg"

-- Special
background="#1c2049"
foreground="#c8e2de"
cursor="#c8e2de"

-- Colors
color0="#1c2049"
color1="#5AB0C4"
color2="#65CBC9"
color3="#A495B3"
color4="#D99BB2"
color5="#A7B7C3"
color6="#D2AEC6"
color7="#c8e2de"
color8="#8c9e9b"
color9="#5AB0C4"
color10="#65CBC9"
color11="#A495B3"
color12="#D99BB2"
color13="#A7B7C3"
color14="#D2AEC6"
color15="#c8e2de"
